name: inpainting
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - cuda100
  - pytorch
  - torchvision=0.4.2
  - matplotlib
  - jupyter
  - pip
  - nvidia-apex
  - pyyaml
  - opencv
  - tensorboard
  - pillow=6.2.0
  - pip:
      - -e .
      - flowiz
      - cupy-cuda101
      - pytorch_lightning
