name: censo
channels:
  - pytorch
dependencies:
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - keras-gpu
  - pytorch
  - torchvision
  - cuda100
  - opencv
  - matplotlib
  - jupyter
  - pip
  - pip:
      - -e .
      - "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
      - "git+https://github.com/matterport/Mask_RCNN.git"
      - "git+https://github.com/jfajkowski/PConv-Keras.git"
      - "git+https://github.com/jfajkowski/edge-connect.git"
