name: deepstab
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - keras-gpu
  - pytorch
  - torchvision
  - opencv
  - matplotlib
  - jupyter
  - pip
  - cupy
  - nvidia-apex
  - requests
  - ignite
  - pip:
      - -e .
      - flowiz
