name: inpainting
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - cudatoolkit
  - torchvision
  - pytorch
  - matplotlib
  - jupyter
  - pip
  - nvidia-apex
  - opencv
  - tensorboard
  - pillow
  - make
  - tqdm
  - pip:
      - -e .
      - flowiz
      - cupy-cuda101
      - pytorch-lightning
      - git+https://github.com/davisvideochallenge/davis2017-evaluation.git
