name: inpainting
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - numpy
  - pandas
  - scikit-image
  - cudatoolkit
  - torchvision
  - pytorch
  - pytorch-lightning
  - tensorboard
  - opencv
  - pillow
  - make
  - tqdm
  - jupyter
  - pip
  - imaug
  - albumentations
  - pip:
      - -e .
      - flowiz
      - cupy-cuda102
